import { describe, expect, it } from 'vitest';
import {
  assertReleaseReady,
  collectDataWarnings,
  listMarkets,
  PricingDataError,
  RATE_CARDS,
  RULESETS,
  selectRateCard,
  selectRuleSet,
  toEffectiveDate,
} from '../index';

describe('ruleset selection', () => {
  it('picks the per-message ruleset through 2026-09-30', () => {
    expect(selectRuleSet('2025-07-01').id).toBe('ruleset-2025-07-01');
    expect(selectRuleSet('2026-09-30').id).toBe('ruleset-2025-07-01');
  });

  it('flips to the October ruleset on the day it takes effect', () => {
    expect(selectRuleSet('2026-10-01').id).toBe('ruleset-2026-10-01');
    expect(selectRuleSet('2030-01-01').id).toBe('ruleset-2026-10-01');
  });

  it('accepts a full ISO datetime and a Date', () => {
    expect(selectRuleSet('2026-10-01T03:00:00.000Z').id).toBe('ruleset-2026-10-01');
    expect(selectRuleSet(new Date('2026-10-01T00:00:00.000Z')).id).toBe('ruleset-2026-10-01');
  });

  it('refuses a date before the dataset starts', () => {
    expect(() => selectRuleSet('2024-01-01')).toThrow(PricingDataError);
  });

  it('refuses a malformed date instead of guessing', () => {
    expect(() => toEffectiveDate('setembro')).toThrow(PricingDataError);
    expect(() => toEffectiveDate(new Date('nope'))).toThrow(PricingDataError);
  });

  it('leaves no gap between consecutive rulesets', () => {
    const ordered = [...RULESETS].sort((a, b) => (a.effectiveFrom < b.effectiveFrom ? -1 : 1));
    for (let i = 0; i < ordered.length - 1; i += 1) {
      const current = ordered[i]!;
      const next = ordered[i + 1]!;
      expect(current.effectiveTo).not.toBeNull();
      const dayAfter = new Date(`${current.effectiveTo!}T00:00:00.000Z`);
      dayAfter.setUTCDate(dayAfter.getUTCDate() + 1);
      expect(dayAfter.toISOString().slice(0, 10)).toBe(next.effectiveFrom);
    }
    expect(ordered[ordered.length - 1]!.effectiveTo).toBeNull();
  });
});

describe('rate card selection', () => {
  it('is case-insensitive about the market code', () => {
    expect(selectRateCard('br', 'BRL', '2026-09-01').market).toBe('BR');
  });

  it('refuses a market it has no data for rather than falling back', () => {
    expect(() => selectRateCard('US', 'USD', '2026-09-01')).toThrow(/no rate card for market=US/);
  });

  it('refuses a date before the card takes effect', () => {
    expect(() => selectRateCard('BR', 'BRL', '2026-06-30')).toThrow(/in force/);
  });

  it('lists its markets for the UI selector', () => {
    expect(listMarkets()).toEqual([{ market: 'BR', currency: 'BRL', name: { pt: 'Brasil', en: 'Brazil' } }]);
  });
});

describe('the shipped Brazilian rate card', () => {
  const card = selectRateCard('BR', 'BRL', '2026-09-01');

  it('carries the rates the spec quotes', () => {
    expect(card.rates).toEqual({ marketing: 0.3217, utility: 0.035, authentication: 0.035 });
    expect(card.currency).toBe('BRL');
    expect(card.effectiveFrom).toBe('2026-07-01');
  });

  it('discounts utility and authentication down to -25%', () => {
    for (const table of card.volumeTiers) {
      expect(table.tiers.map((t) => t.discountPct)).toEqual([0, 5, 10, 15, 20, 25]);
      expect(table.tiers.map((t) => t.rate)).toEqual([0.035, 0.0333, 0.0315, 0.0298, 0.028, 0.0263]);
    }
  });

  it('keeps every tier table contiguous, ordered and open-ended at the top', () => {
    for (const table of card.volumeTiers) {
      expect(table.tiers[0]!.from).toBe(0);
      for (let i = 0; i < table.tiers.length - 1; i += 1) {
        const tier = table.tiers[i]!;
        expect(tier.to).not.toBeNull();
        expect(tier.to).toBe(table.tiers[i + 1]!.from);
        expect(tier.rate).toBeGreaterThan(table.tiers[i + 1]!.rate);
      }
      expect(table.tiers[table.tiers.length - 1]!.to).toBeNull();
    }
  });

  it('states every discounted rate as the published percentage off the list rate', () => {
    for (const table of card.volumeTiers) {
      const list = card.rates[table.category];
      for (const tier of table.tiers) {
        const expected = Math.round(list * (1 - tier.discountPct / 100) * 10_000) / 10_000;
        expect(tier.rate).toBe(expected);
      }
    }
  });
});

describe('verification flags', () => {
  it('has every shipped rate and threshold sourced from Meta', () => {
    // Regenerated by scripts/fetch-rate-card.mjs from Meta's own published pricing data.
    const card = selectRateCard('BR', 'BRL', '2026-09-01');
    expect(card.ratesVerified).toBe(true);
    expect(card.volumeTiers.every((t) => t.tiersVerified)).toBe(true);
  });

  it('raises no data warnings for a fully sourced market', () => {
    const warnings = collectDataWarnings(selectRateCard('BR', 'BRL', '2026-09-01'), selectRuleSet('2026-09-01'));
    expect(warnings).toEqual([]);
  });

  it('still turns an unverified flag into a warning consumers can render', () => {
    // The mechanism has to keep working for the next market someone contributes, so it is
    // exercised against a fabricated card rather than against whatever ships today.
    const unsourced = {
      ...selectRateCard('BR', 'BRL', '2026-09-01'),
      ratesVerified: false,
      volumeTiers: [{ category: 'utility' as const, tiersVerified: false, tiers: [] }],
    };
    const warnings = collectDataWarnings(unsourced, selectRuleSet('2026-09-01'));
    expect(warnings.map((w) => w.code)).toContain('TIERS_UNVERIFIED');
    expect(warnings.map((w) => w.code)).toContain('RATES_UNVERIFIED');
    for (const warning of warnings) {
      expect(warning.message.pt.length).toBeGreaterThan(10);
      expect(warning.message.en.length).toBeGreaterThan(10);
    }
  });

  it('lets a release through now that nothing is a placeholder', () => {
    expect(() => assertReleaseReady()).not.toThrow();
  });

  it('gives every card and ruleset a primary source URL', () => {
    for (const card of RATE_CARDS) expect(card.sourceUrl).toMatch(/^https:\/\//);
    for (const rules of RULESETS) expect(rules.sourceUrl).toMatch(/^https:\/\//);
  });

  it('records when each file was last checked against that source', () => {
    // The README badge quotes this, and a dataset that cannot say when it was last
    // checked is a dataset nobody should trust with a pricing decision.
    for (const card of RATE_CARDS) {
      expect(card.verifiedAt, `${card.market}/${card.currency}`).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(card.verifiedAt >= card.effectiveFrom, `${card.market}: checked before it took effect`).toBe(true);
    }
    for (const rules of RULESETS) {
      expect(rules.verifiedAt, rules.id).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });
});

describe('the shipped tier thresholds', () => {
  const card = selectRateCard('BR', 'BRL', '2026-09-01');
  const table = (category: 'utility' | 'authentication') =>
    card.volumeTiers.find((t) => t.category === category)!;

  it('matches what Meta publishes for utility', () => {
    expect(table('utility').tiers.map((t) => [t.from, t.to, t.rate])).toEqual([
      [0, 250_000, 0.035],
      [250_000, 2_000_000, 0.0333],
      [2_000_000, 17_000_000, 0.0315],
      [17_000_000, 35_000_000, 0.0298],
      [35_000_000, 70_000_000, 0.028],
      [70_000_000, null, 0.0263],
    ]);
  });

  it('matches what Meta publishes for authentication, which is a different table', () => {
    expect(table('authentication').tiers.map((t) => [t.from, t.to, t.rate])).toEqual([
      [0, 500_000, 0.035],
      [500_000, 3_000_000, 0.0333],
      [3_000_000, 5_250_000, 0.0315],
      [5_250_000, 10_000_000, 0.0298],
      [10_000_000, 20_000_000, 0.028],
      [20_000_000, null, 0.0263],
    ]);
    // The two categories share list rates and discounts but not thresholds — authentication
    // reaches each discount later. Treating them as one table would misprice both.
    expect(table('authentication').tiers[0]!.to).not.toBe(table('utility').tiers[0]!.to);
  });
});
